toolbar:
  - styleselect | bold italic | link image | undo redo
  - table | fullscreen
plugins:
  - table
  - fullscreen
  - wordcount
  - autosave
  - link
  - code
  - image
width: 700
resize: 'both'
statusbar: true